/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-15 09:04:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Tools/apache-tomcat-8.5.43/webapps/fly-0.0.1-SNAPSHOT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/user/../common/link.jsp", Long.valueOf(1574778172000L));
    _jspx_dependants.put("jar:file:/C:/Tools/apache-tomcat-8.5.43/webapps/fly-0.0.1-SNAPSHOT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/user/../common/header.jsp", Long.valueOf(1576330684000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1574084526000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fn_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fn_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>我的消息</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- fly基础样式 -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/global.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-header layui-bg-black\">\r\n");
      out.write("  <div class=\"layui-container\">\r\n");
      out.write("    <a class=\"fly-logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/logo.png\" alt=\"layui\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"layui-nav fly-nav layui-hide-xs\">\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"layui-nav fly-nav-user\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- 未登入的状态 -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_n_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("\t   ");
      if (_jspx_meth_n_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layui-container fly-marginTop fly-user-main\">\r\n");
      out.write("  <ul class=\"layui-nav layui-nav-tree layui-inline\" lay-filter=\"user\">\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe609;</i>\r\n");
      out.write("        我的主页\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe612;</i>\r\n");
      out.write("        用户中心\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/set\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe620;</i>\r\n");
      out.write("        基本设置\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item layui-this\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/message\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe611;</i>\r\n");
      out.write("        我的消息\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-tree-mobile layui-hide\">\r\n");
      out.write("    <i class=\"layui-icon\">&#xe602;</i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"site-mobile-shade\"></div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"site-tree-mobile layui-hide\">\r\n");
      out.write("    <i class=\"layui-icon\">&#xe602;</i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"site-mobile-shade\"></div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"fly-panel fly-panel-user\" pad20>\r\n");
      out.write("\t  <div class=\"layui-tab layui-tab-brief\" lay-filter=\"user\" id=\"LAY_msg\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t    <button class=\"layui-btn layui-btn-danger\" id=\"LAY_delallmsg\">清空全部消息</button>\r\n");
      out.write("\t    <div  id=\"LAY_minemsg\" style=\"margin-top: 10px;\">\r\n");
      out.write("        <!--<div class=\"fly-none\">您暂时没有最新消息</div>-->\r\n");
      out.write("        <ul class=\"mine-msg\">\r\n");
      out.write("          <li data-id=\"123\">\r\n");
      out.write("            <blockquote class=\"layui-elem-quote\">\r\n");
      out.write("              <a href=\"/jump?username=Absolutely\" target=\"_blank\"><cite>Absolutely</cite></a>回答了您的求解<a target=\"_blank\" href=\"/jie/8153.html/page/0/#item-1489505778669\"><cite>layui后台框架</cite></a>\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p><span>1小时前</span><a href=\"javascript:;\" class=\"layui-btn layui-btn-small layui-btn-danger fly-delete\">删除</a></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li data-id=\"123\">\r\n");
      out.write("            <blockquote class=\"layui-elem-quote\">\r\n");
      out.write("              系统消息：欢迎使用 layui\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p><span>1小时前</span><a href=\"javascript:;\" class=\"layui-btn layui-btn-small layui-btn-danger fly-delete\">删除</a></p>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\" target=\"_blank\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\" target=\"_blank\">layui.com 出品</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/3147/\" target=\"_blank\">付费计划</a>\r\n");
      out.write("    <a href=\"http://www.layui.com/template/fly/\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461/\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'user';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"3.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_n_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  n:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_n_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_n_005fif_005f0_reused = false;
    try {
      _jspx_th_n_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_n_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/user/../common/header.jsp(26,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_n_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2 == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_n_005fif_005f0 = _jspx_th_n_005fif_005f0.doStartTag();
      if (_jspx_eval_n_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a class=\"iconfont icon-touxiang layui-hide-xs\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">登入</a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/reg\">注册</a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item layui-hide-xs\">\r\n");
          out.write("\t        <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" title=\"QQ登入\" class=\"iconfont icon-qq\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item layui-hide-xs\">\r\n");
          out.write("\t        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" title=\"微博登入\" class=\"iconfont icon-weibo\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t   ");
          int evalDoAfterBody = _jspx_th_n_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_n_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.reuse(_jspx_th_n_005fif_005f0);
      _jspx_th_n_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_n_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_n_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_n_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  n:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_n_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_n_005fif_005f1_reused = false;
    try {
      _jspx_th_n_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_n_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/user/../common/header.jsp(44,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_n_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2 != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_n_005fif_005f1 = _jspx_th_n_005fif_005f1.doStartTag();
      if (_jspx_eval_n_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a class=\"fly-nav-avatar\" href=\"javascript:;\">\r\n");
          out.write("\t          <cite class=\"layui-hide-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2.nick_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</cite>\r\n");
          out.write("\t          <i class=\"iconfont icon-renzheng layui-hide-xs\" title=\"认证信息：layui 作者\"></i>\r\n");
          out.write("\t          <i class=\"layui-badge fly-badge-vip layui-hide-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.level.level_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</i>\r\n");
          out.write("\t             <!-- 头像 Start -->   \r\n");
          out.write("\t                ");
          if (_jspx_meth_fx_005fif_005f0(_jspx_th_n_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t                ");
          if (_jspx_meth_fx_005fif_005f1(_jspx_th_n_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t              <!-- 头像 End -->   \r\n");
          out.write("\t        </a>\r\n");
          out.write("\t        <dl class=\"layui-nav-child\">\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/set\"><i class=\"layui-icon\">&#xe620;</i>基本设置</a></dd>\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/message\"><i class=\"iconfont icon-tongzhi\" style=\"top: 4px;\"></i>我的消息</a></dd>\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/home\"><i class=\"layui-icon\" style=\"margin-left: 2px; font-size: 22px;\">&#xe68e;</i>我的主页</a></dd>\r\n");
          out.write("\t          <hr style=\"margin: 5px 0;\">\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\" style=\"text-align: center;\">退出</a></dd>\r\n");
          out.write("\t        </dl>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t    ");
          int evalDoAfterBody = _jspx_th_n_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_n_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.reuse(_jspx_th_n_005fif_005f1);
      _jspx_th_n_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_n_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_n_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fx_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_n_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fx:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_fx_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_fx_005fif_005f0_reused = false;
    try {
      _jspx_th_fx_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fx_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_n_005fif_005f1);
      // /WEB-INF/jsp/user/../common/header.jsp(51,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fx_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath == ''|| imgpath == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_fx_005fif_005f0 = _jspx_th_fx_005fif_005f0.doStartTag();
      if (_jspx_eval_fx_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                \t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/res/avatar/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2.avatar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t                ");
          int evalDoAfterBody = _jspx_th_fx_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_fx_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.reuse(_jspx_th_fx_005fif_005f0);
      _jspx_th_fx_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fx_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_fx_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fx_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_n_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fx:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_fx_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_fx_005fif_005f1_reused = false;
    try {
      _jspx_th_fx_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fx_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_n_005fif_005f1);
      // /WEB-INF/jsp/user/../common/header.jsp(54,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fx_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath == customer2.avatar}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_fx_005fif_005f1 = _jspx_th_fx_005fif_005f1.doStartTag();
      if (_jspx_eval_fx_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                \t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/res/avatar/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t                ");
          int evalDoAfterBody = _jspx_th_fx_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_fx_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.reuse(_jspx_th_fx_005fif_005f1);
      _jspx_th_fx_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fx_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_fx_005fif_005f1_reused);
    }
    return false;
  }
}
