/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-15 05:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.jie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Tools/apache-tomcat-8.5.43/webapps/fly-0.0.1-SNAPSHOT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/jie/../common/link.jsp", Long.valueOf(1574778172000L));
    _jspx_dependants.put("jar:file:/C:/Tools/apache-tomcat-8.5.43/webapps/fly-0.0.1-SNAPSHOT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/jie/../common/header.jsp", Long.valueOf(1576330684000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1574084526000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fn_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fn_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- fly基础样式 -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/global.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-header layui-bg-black\">\r\n");
      out.write("  <div class=\"layui-container\">\r\n");
      out.write("    <a class=\"fly-logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/logo.png\" alt=\"layui\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"layui-nav fly-nav layui-hide-xs\">\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"layui-nav fly-nav-user\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- 未登入的状态 -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_n_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("\t   ");
      if (_jspx_meth_n_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layui-container\">\r\n");
      out.write("  <div class=\"layui-row layui-col-space15\">\r\n");
      out.write("    <div class=\"layui-col-md8 content detail\">\r\n");
      out.write("      <div class=\"fly-panel detail-box\">\r\n");
      out.write("        <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("        <div class=\"fly-detail-info\">\r\n");
      out.write("        \t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"num\">\r\n");
      out.write("          <!-- <span class=\"layui-badge\">审核中</span> -->\r\n");
      out.write("          <span class=\"layui-badge layui-bg-green fly-detail-column\">动态</span>\r\n");
      out.write("          \r\n");
      out.write("          <span class=\"layui-badge\" style=\"background-color: #999;\">未结</span>\r\n");
      out.write("          <!-- <span class=\"layui-badge\" style=\"background-color: #5FB878;\">已结</span> -->\r\n");
      out.write("          \r\n");
      out.write("          <span class=\"layui-badge layui-bg-black\">置顶</span>\r\n");
      out.write("          <span class=\"layui-badge layui-bg-red\">精帖</span>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"fly-admin-box\" data-id=\"123\">\r\n");
      out.write("            <!-- <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"del\">删除</span> -->\r\n");
      out.write("            <a class=\"layui-btn layui-btn-xs\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/del/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onClick=\"return confirm('确认删除该求解么？');\">删除</a>\r\n");
      out.write("            \r\n");
      out.write("            <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"set\" field=\"stick\" rank=\"1\">置顶</span> \r\n");
      out.write("            <!-- <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"set\" field=\"stick\" rank=\"0\" style=\"background-color:#ccc;\">取消置顶</span> -->\r\n");
      out.write("            \r\n");
      out.write("            <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"set\" field=\"status\" rank=\"1\">加精</span> \r\n");
      out.write("            <!-- <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"set\" field=\"status\" rank=\"0\" style=\"background-color:#ccc;\">取消加精</span> -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"fly-list-nums\"> \r\n");
      out.write("            <a href=\"#comment\"><i class=\"iconfont\" title=\"回答\">&#xe60c;</i> 66</a>\r\n");
      out.write("            <i class=\"iconfont\" title=\"人气\">&#xe60b;</i> \r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"detail-about\">\r\n");
      out.write("          <a class=\"fly-avatar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/home\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/avatar/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.customer.avatar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.customer.signature}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"fly-detail-user\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/home\" class=\"fly-link\">\r\n");
      out.write("              <cite>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.customer.nick_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</cite>\r\n");
      out.write("              <i class=\"iconfont icon-renzheng\" ></i><!-- title=\"认证信息：{{ rows.user.approve }}\" -->\r\n");
      out.write("              <i class=\"layui-badge fly-badge-vip\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.level.level_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.level.level_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${create_time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"detail-hits\" id=\"LAY_jieAdmin\" data-id=\"123\">\r\n");
      out.write("            <span style=\"padding-right: 10px; color: #FF7200\">悬赏：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.kiss.kiss_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>  \r\n");
      out.write("            <span class=\"layui-btn layui-btn-xs jie-admin\" type=\"edit\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edit/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" target=\"_blank\">编辑此贴</a></span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"detail-body photos\">\r\n");
      out.write("\t\t  <p>\r\n");
      out.write("\t\t  \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumcontext.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t  </p>\r\n");
      out.write("<!--           <p>更新日志：</p>\r\n");
      out.write("<pre>\r\n");
      out.write("# v3.0 2017-11-30\r\n");
      out.write("* 采用 layui 2.2.3 作为 UI 支撑\r\n");
      out.write("* 全面同步最新的 Fly 社区风格，各种细节得到大幅优化\r\n");
      out.write("* 更友好的响应式适配能力\r\n");
      out.write("</pre> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"fly-panel detail-box\" id=\"flyReply\">\r\n");
      out.write("        <fieldset class=\"layui-elem-field layui-field-title\" style=\"text-align: center;\">\r\n");
      out.write("          <legend>回帖</legend>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"jieda\" id=\"jieda\">\r\n");
      out.write("          <li data-id=\"111\" class=\"jieda-daan\">\r\n");
      out.write("            <a name=\"item-1111111111\"></a>\r\n");
      out.write("            <div class=\"detail-about detail-about-reply\">\r\n");
      out.write("              <a class=\"fly-avatar\" href=\"\">\r\n");
      out.write("                <img src=\"https://tva1.sinaimg.cn/crop.0.0.118.118.180/5db11ff4gw1e77d3nqrv8j203b03cweg.jpg\" alt=\" \">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"fly-detail-user\">\r\n");
      out.write("                <a href=\"\" class=\"fly-link\">\r\n");
      out.write("                  <cite>贤心</cite>\r\n");
      out.write("                  <i class=\"iconfont icon-renzheng\" title=\"认证信息：XXX\"></i>\r\n");
      out.write("                  <i class=\"layui-badge fly-badge-vip\">VIP3</i>              \r\n");
      out.write("                </a>\r\n");
      out.write("                \r\n");
      out.write("                <span>(楼主)</span>\r\n");
      out.write("                <!--\r\n");
      out.write("                <span style=\"color:#5FB878\">(管理员)</span>\r\n");
      out.write("                <span style=\"color:#FF9E3F\">（社区之光）</span>\r\n");
      out.write("                <span style=\"color:#999\">（该号已被封）</span>\r\n");
      out.write("                -->\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"detail-hits\">\r\n");
      out.write("                <span>2017-11-30</span>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <i class=\"iconfont icon-caina\" title=\"最佳答案\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"detail-body jieda-body photos\">\r\n");
      out.write("              <p>香菇那个蓝瘦，这是一条被采纳的回帖</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"jieda-reply\">\r\n");
      out.write("              <span class=\"jieda-zan zanok\" type=\"zan\">\r\n");
      out.write("                <i class=\"iconfont icon-zan\"></i>\r\n");
      out.write("                <em>66</em>\r\n");
      out.write("              </span>\r\n");
      out.write("              <span type=\"reply\">\r\n");
      out.write("                <i class=\"iconfont icon-svgmoban53\"></i>\r\n");
      out.write("                回复\r\n");
      out.write("              </span>\r\n");
      out.write("              <div class=\"jieda-admin\">\r\n");
      out.write("                <span type=\"edit\">编辑</span>\r\n");
      out.write("                <span type=\"del\">删除</span>\r\n");
      out.write("                <!-- <span class=\"jieda-accept\" type=\"accept\">采纳</span> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li data-id=\"111\">\r\n");
      out.write("            <a name=\"item-1111111111\"></a>\r\n");
      out.write("            <div class=\"detail-about detail-about-reply\">\r\n");
      out.write("              <a class=\"fly-avatar\" href=\"\">\r\n");
      out.write("                <img src=\"https://tva1.sinaimg.cn/crop.0.0.118.118.180/5db11ff4gw1e77d3nqrv8j203b03cweg.jpg\" alt=\" \">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"fly-detail-user\">\r\n");
      out.write("                <a href=\"\" class=\"fly-link\">\r\n");
      out.write("                  <cite>贤心</cite>       \r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"detail-hits\">\r\n");
      out.write("                <span>2017-11-30</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"detail-body jieda-body photos\">\r\n");
      out.write("              <p>蓝瘦那个香菇，这是一条没被采纳的回帖</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"jieda-reply\">\r\n");
      out.write("              <span class=\"jieda-zan\" type=\"zan\">\r\n");
      out.write("                <i class=\"iconfont icon-zan\"></i>\r\n");
      out.write("                <em>0</em>\r\n");
      out.write("              </span>\r\n");
      out.write("              <span type=\"reply\">\r\n");
      out.write("                <i class=\"iconfont icon-svgmoban53\"></i>\r\n");
      out.write("                回复\r\n");
      out.write("              </span>\r\n");
      out.write("              <div class=\"jieda-admin\">\r\n");
      out.write("                <span type=\"edit\">编辑</span>\r\n");
      out.write("                <span type=\"del\">删除</span>\r\n");
      out.write("                <span class=\"jieda-accept\" type=\"accept\">采纳</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <!-- 无数据时 -->\r\n");
      out.write("          <!-- <li class=\"fly-none\">消灭零回复</li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"layui-form layui-form-pane\">\r\n");
      out.write("          <form action=\"/jie/reply/\" method=\"post\">\r\n");
      out.write("            <div class=\"layui-form-item layui-form-text\">\r\n");
      out.write("              <a name=\"comment\"></a>\r\n");
      out.write("              <div class=\"layui-input-block\">\r\n");
      out.write("                <textarea id=\"L_content\" name=\"content\" required lay-verify=\"required\" placeholder=\"请输入内容\"  class=\"layui-textarea fly-editor\" style=\"height: 150px;\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <input type=\"hidden\" name=\"jid\" value=\"123\">\r\n");
      out.write("              <button class=\"layui-btn\" lay-filter=\"*\" lay-submit>提交回复</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"layui-col-md4\">\r\n");
      out.write("      <dl class=\"fly-panel fly-list-one\">\r\n");
      out.write("        <dt class=\"fly-panel-title\">本周热议</dt>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"\">基于 layui 的极简社区页面模版</a>\r\n");
      out.write("          <span><i class=\"iconfont icon-pinglun1\"></i> 16</span>\r\n");
      out.write("        </dd>\r\n");
      out.write("\r\n");
      out.write("        <!-- 无数据时 -->\r\n");
      out.write("        <!--\r\n");
      out.write("        <div class=\"fly-none\">没有相关数据</div>\r\n");
      out.write("        -->\r\n");
      out.write("      </dl>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"fly-panel\">\r\n");
      out.write("        <div class=\"fly-panel-title\">\r\n");
      out.write("          这里可作为广告区域\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fly-panel-main\">\r\n");
      out.write("          <a href=\"http://layim.layui.com/?from=fly\" target=\"_blank\" class=\"fly-zanzhu\" time-limit=\"2017.09.25-2099.01.01\" style=\"background-color: #5FB878;\">LayIM 3.0 - layui 旗舰之作</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"fly-panel\" style=\"padding: 20px 0; text-align: center;\">\r\n");
      out.write("        <img src=\"../../res/images/weixin.jpg\" style=\"max-width: 100%;\" alt=\"layui\">\r\n");
      out.write("        <p style=\"position: relative; color: #666;\">微信扫码关注 layui 公众号</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\" target=\"_blank\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\" target=\"_blank\">layui.com 出品</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/3147/\" target=\"_blank\">付费计划</a>\r\n");
      out.write("    <a href=\"http://www.layui.com/template/fly/\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461/\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'jie';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"3.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use(['fly', 'face'], function(){\r\n");
      out.write("  var $ = layui.$\r\n");
      out.write("  ,fly = layui.fly;\r\n");
      out.write("  //如果你是采用模版自带的编辑器，你需要开启以下语句来解析。\r\n");
      out.write("  /*\r\n");
      out.write("  $('.detail-body').each(function(){\r\n");
      out.write("    var othis = $(this), html = othis.html();\r\n");
      out.write("    othis.html(fly.content(html));\r\n");
      out.write("  });\r\n");
      out.write("  */\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_n_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  n:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_n_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_n_005fif_005f0_reused = false;
    try {
      _jspx_th_n_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_n_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/jie/../common/header.jsp(26,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_n_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2 == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_n_005fif_005f0 = _jspx_th_n_005fif_005f0.doStartTag();
      if (_jspx_eval_n_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a class=\"iconfont icon-touxiang layui-hide-xs\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">登入</a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/reg\">注册</a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item layui-hide-xs\">\r\n");
          out.write("\t        <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" title=\"QQ登入\" class=\"iconfont icon-qq\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t      <li class=\"layui-nav-item layui-hide-xs\">\r\n");
          out.write("\t        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" title=\"微博登入\" class=\"iconfont icon-weibo\"></a>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t   ");
          int evalDoAfterBody = _jspx_th_n_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_n_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.reuse(_jspx_th_n_005fif_005f0);
      _jspx_th_n_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_n_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_n_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_n_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  n:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_n_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_n_005fif_005f1_reused = false;
    try {
      _jspx_th_n_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_n_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/jie/../common/header.jsp(44,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_n_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2 != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_n_005fif_005f1 = _jspx_th_n_005fif_005f1.doStartTag();
      if (_jspx_eval_n_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t      <li class=\"layui-nav-item\">\r\n");
          out.write("\t        <a class=\"fly-nav-avatar\" href=\"javascript:;\">\r\n");
          out.write("\t          <cite class=\"layui-hide-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2.nick_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</cite>\r\n");
          out.write("\t          <i class=\"iconfont icon-renzheng layui-hide-xs\" title=\"认证信息：layui 作者\"></i>\r\n");
          out.write("\t          <i class=\"layui-badge fly-badge-vip layui-hide-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.level.level_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</i>\r\n");
          out.write("\t             <!-- 头像 Start -->   \r\n");
          out.write("\t                ");
          if (_jspx_meth_fx_005fif_005f0(_jspx_th_n_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t                ");
          if (_jspx_meth_fx_005fif_005f1(_jspx_th_n_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t              <!-- 头像 End -->   \r\n");
          out.write("\t        </a>\r\n");
          out.write("\t        <dl class=\"layui-nav-child\">\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/set\"><i class=\"layui-icon\">&#xe620;</i>基本设置</a></dd>\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/message\"><i class=\"iconfont icon-tongzhi\" style=\"top: 4px;\"></i>我的消息</a></dd>\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/home\"><i class=\"layui-icon\" style=\"margin-left: 2px; font-size: 22px;\">&#xe68e;</i>我的主页</a></dd>\r\n");
          out.write("\t          <hr style=\"margin: 5px 0;\">\r\n");
          out.write("\t          <dd><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\" style=\"text-align: center;\">退出</a></dd>\r\n");
          out.write("\t        </dl>\r\n");
          out.write("\t      </li>\r\n");
          out.write("\t    ");
          int evalDoAfterBody = _jspx_th_n_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_n_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fn_005fif_0026_005ftest.reuse(_jspx_th_n_005fif_005f1);
      _jspx_th_n_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_n_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_n_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fx_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_n_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fx:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_fx_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_fx_005fif_005f0_reused = false;
    try {
      _jspx_th_fx_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fx_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_n_005fif_005f1);
      // /WEB-INF/jsp/jie/../common/header.jsp(51,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fx_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath == ''|| imgpath == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_fx_005fif_005f0 = _jspx_th_fx_005fif_005f0.doStartTag();
      if (_jspx_eval_fx_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                \t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/res/avatar/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer2.avatar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t                ");
          int evalDoAfterBody = _jspx_th_fx_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_fx_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.reuse(_jspx_th_fx_005fif_005f0);
      _jspx_th_fx_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fx_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_fx_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fx_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_n_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fx:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_fx_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_fx_005fif_005f1_reused = false;
    try {
      _jspx_th_fx_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fx_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_n_005fif_005f1);
      // /WEB-INF/jsp/jie/../common/header.jsp(54,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fx_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath == customer2.avatar}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_fx_005fif_005f1 = _jspx_th_fx_005fif_005f1.doStartTag();
      if (_jspx_eval_fx_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                \t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/res/avatar/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t                ");
          int evalDoAfterBody = _jspx_th_fx_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_fx_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffx_005fif_0026_005ftest.reuse(_jspx_th_fx_005fif_005f1);
      _jspx_th_fx_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fx_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_fx_005fif_005f1_reused);
    }
    return false;
  }
}
